Feature/participate in match
fabioheiji/engenhariaSI pull request #27
Opened 2022-10-25 16:48 UTC by fabioheiji

2022-10-25 23:33 UTC, vitormrts requested changes

2022-10-25 23:33 UTC, vitormrts commented on .gitignore
> +/.github/workflows/ruby.yml
Temos que rever isto. Colocar o workflow do github actions no gitignore o fará para de funcionar.

2022-10-25 23:33 UTC, vitormrts commented on config/database.yml
> +  username: postgres
Consegue voltar para username bighash? Pode ser que o projeto que já está funcionando nas máquinas dos participantes deixe de funcionar com isso

2022-10-25 23:46 UTC, fabioheiji commented on .gitignore
> +/.github/workflows/ruby.yml
Ok. Farei isso sim é já subo novo push

2022-10-25 23:47 UTC, fabioheiji commented on config/database.yml
> +  username: postgres
Blz! Eu altero sim. Eu tinha configurado desta forma lá no começo quando tínhamos mudado para postgresql. Mais tarde já faço uma nova PR.

2022-10-26 20:13 UTC, vitormrts approved these changes

2022-10-26 20:17 UTC, merged